### ISSUE TITLE
Model fine tuning 

### ISSUE THREAD

**Issue by wjs20** [amyxlu/CPCProt#3]
Hi! model looks really interesting. I'd like to do some fine tuning on local context, like what is suggested by fastai
![image](https://user-images.githubusercontent.com/70591703/100271430-5fbcd780-2f51-11eb-8ed2-43ab001905ef.png)
Can you give me advice on how to do so with your model? The fine tuning example you have provided seems only to suggest adding a classifier head to the model.

Thanks

**Comment by amyxlu** [comment]
Hi, thanks for your message! If you would like to finetune on local context, using the classifier head as given in the example would suffice (i.e. the classifier head is your classifier in this schematic). Alternatively, you may also extract the embeddings and fit another classifier (e.g. a simple logistic regression classifier) on top of these embeddings, without updating encoder weights when training this classifier.
